apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: navigator-elasticsearch-sysctl
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: navigator-elasticsearch-sysctl
  template:
    metadata:
      labels:
        name: navigator-elasticsearch-sysctl
    spec:
      containers:
      - name: apply-sysctl
        image: busybox:latest
        resources:
          limits:
            cpu: 10m
            memory: 8Mi
          requests:
            cpu: 10m
            memory: 8Mi
        securityContext:
          privileged: true
        command:
        - /bin/sh
        - -c
        - |
          set -o errexit
          set -o xtrace
          while sysctl -w vm.max_map_count=262144
          do
            sleep 60s
          done