#ELK deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1-deployment
  labels:
    app: microservice1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
      - name: microservice1-service
        image: zahwaar/microservice1:1.0
        ports:
        - containerPort: 8001
---
kind: Service
apiVersion: v1
metadata:
  name: microservice1
spec:
  type: LoadBalancer
  selector:
    app: microservice1
  ports:
  - port: 80
    targetPort: 8001