apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  labels:
    app: elk
spec:
  selector:
    app: elk
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5601
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: elastic-svc
  labels:
    app: elk
spec:
  selector:
    app: elk
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
  type: ClusterIP